# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='led_wattage',
            field=models.CharField(choices=[('S', '6_watt'), ('N', '9_watt'), ('TW', '12_watt')], max_length=3),
        ),
    ]
