# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('led', '0002_auto_20170604_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='led_wattage',
            field=models.CharField(choices=[('S', 'Six_watt'), ('N', 'Nine_watt'), ('TW', 'Twelve_watt')], max_length=3),
        ),
    ]
